CREATE TABLE "child" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "date_of_birth" datetime,
  "date_of_diagnosis" datetime,
  "notes" text
);

CREATE TABLE "observer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "relation" varchar,
  "notes" text
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar
);

CREATE TABLE "behavior_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "is_milestone" bool,
  "description" varchar
);

CREATE TABLE "behavior_entry" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "child_id" int,
  "observer_id" int,
  "behavior_type_id" int,
  "category_id" int,
  "behavior_date" datetime,
  "notes" text,
  "duration_sec" int,
  "consolidated" bool,
  "base" bool
);

CREATE TABLE "alert" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "child_id" int,
  "alert_date" datetime,
  "solved" bool,
  "description" text
);

CREATE TABLE "translation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "language_code" varchar,
  "original_text" varchar,
  "translated_text" varchar
);

ALTER TABLE "behavior_entry" ADD FOREIGN KEY ("child_id") REFERENCES "child" ("id");

ALTER TABLE "behavior_entry" ADD FOREIGN KEY ("observer_id") REFERENCES "observer" ("id");

ALTER TABLE "behavior_entry" ADD FOREIGN KEY ("behavior_type_id") REFERENCES "behavior_type" ("id");

ALTER TABLE "behavior_entry" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");

ALTER TABLE "alert" ADD FOREIGN KEY ("child_id") REFERENCES "child" ("id");

ALTER TABLE "observer" ADD FOREIGN KEY ("id") REFERENCES "observer" ("relation");
